#!/usr/bin/env python3
"""Apply simple-English definitions to every remaining miss note."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
from apply_definition import apply_definition  # noqa: E402

DEFS: dict[str, str] = {
    "AGENTS.md": "Cursor agent guide for this Obsidian vault — what the repo is and how to work in it.",
    "AWS.md": "Amazon Web Services folder hub — cloud compute, storage, networking, and IAM notes.",
    "AWS/AMI (Amazon Machine Image).md": "AMI (Amazon Machine Image) — pre-built disk image used to launch an EC2 instance.",
    "AWS/AWS EFS (Elastic File System).md": "EFS (Elastic File System) — shared NFS file storage that many EC2s can mount at once.",
    "AWS/AWS cli commands.md": "Common `aws` CLI commands for identity, IAM, EC2, and filtered queries.",
    "AWS/AWS cli installation.md": "Install and configure the AWS CLI v2 on Linux, including shell autocomplete.",
    "AWS/EBS (Elastic Block Store).md": "EBS (Elastic Block Store) — durable block disk attached to one EC2 instance.",
    "AWS/aws host website.md": "Turn an S3 bucket into a static website with index and error documents.",
    "Architectures/H3 (Hexagonal Hierarchical Spatial Index).md": "H3 — Uber’s hex grid that indexes Earth locations for fast geospatial queries.",
    "Architectures/Idempotent-key.md": "Client-sent unique key so retries of the same request do not create duplicate resources.",
    "Architectures/Live Streaming Architecture Multi-Channel Distribution at 1M Concurrent User.md": "How to serve many live TV channels to ~1M viewers using origin + CDN edge caching.",
    "Architectures/Service Layer.md": "App layer that holds business rules between HTTP/UI controllers and the database.",
    "Architectures/System Architecture.md": "Modular system design — register only the parts you need to keep bundles small.",
    "Architectures/When scaling to hundreds of concurrent channels.md": "Bottlenecks and tuning when encoding or serving hundreds of live channels at once.",
    "Architectures/database/MVCC.md": "MVCC (Multi-Version Concurrency Control) — readers see a snapshot so reads do not block writes.",
    "Architectures/database/OCC.md": "OCC (Optimistic Concurrency Control) — run without locks, then abort if someone else wrote first.",
    "Architectures/feature flag.md": "Remote on/off switch for a feature so you can ship code dark and release safely.",
    "Architectures/frontend layered architecture.md": "Folder layout that separates UI, state, and data access in a frontend app.",
    "Architectures/presentation layer.md": "UI/API edge of the app — talks to the service layer, never straight to the database.",
    "Broadcast.md": "One sender to every device on the same LAN broadcast domain.",
    "CDM (Content Decryption Module).md": "CDM (Content Decryption Module) — browser/OS piece that unlocks DRM-protected media.",
    "Code review.md": "Checklist habits for reviewing PRs — correctness, security, and clear feedback.",
    "Common Naming terms.md": "Short glossary of common engineering names (daemon, service, agent, and similar).",
    "DNS/DNS server.md": "DNS (Domain Name System) server — answers name lookups so clients find IP addresses.",
    "DNS/LLMNR.md": "LLMNR (Link-Local Multicast Name Resolution) — local-only name lookup on a LAN without a DNS server.",
    "DNS/Sub Domain.md": "A name under a parent domain (like api.example.com) with its own DNS records.",
    "DNS/Unbound.md": "Open-source recursive DNS resolver with caching and DNSSEC validation.",
    "DNS/name server.md": "Authoritative DNS host that stores and serves the official records for a domain.",
    "DNS/public resolver.md": "Public recursive DNS (8.8.8.8, 1.1.1.1) that looks up names on behalf of clients.",
    "DNS/servers/CoreDNS.md": "Plugin-based DNS server written in Go — default cluster DNS in Kubernetes.",
    "DNS/servers/DSN records.md": "DNS record types (A, AAAA, CNAME, MX, TXT, …) that map names to routing data.",
    "DNS/servers/PoserDNS.md": "PowerDNS — high-performance open-source DNS with separate authoritative and recursive roles.",
    "DNS/servers/dnsmasq.md": "Small DNS/DHCP/TFTP helper often used on home routers and lab networks.",
    "Data structure/ADT (Abstract Data Type).md": "ADT (Abstract Data Type) — describes behavior (stack, queue) without fixing the implementation.",
    "Data structure/DSA algorithms.md": "How to reason about algorithm time and space as input size grows.",
    "Data structure/Data structure.md": "Ways to organize data in memory so reads and updates stay efficient.",
    "Data structure/Questions.md": "Practice DSA problems and patterns for interviews and drills.",
    "Data structure/Sorting algorithm.md": "Algorithms that reorder a collection — pick by average cost and stability needs.",
    "Data structure/algo/Two pointer.md": "Two moving indexes on a sequence to scan or pair elements in linear time.",
    "Data structure/array.md": "Contiguous indexed collection — O(1) access by position; costly middle inserts.",
    "Data structure/dsa intuition.md": "How to think like a state machine when inventing an algorithm step by step.",
    "Data structure/dsa modular arithmetics.md": "Clock-style math with remainders — wrap values with mod for hashes and cycles.",
    "Data structure/dsa problem solving Scaffold.md": "Repeatable steps: read constraints, pick a pattern, code, then prove complexity.",
    "DevOps/Architectural backend design principles.md": "Principles for backend shape — clear interfaces, isolation, and operable defaults.",
    "DevOps/Edge orchestration tools for industrial IoT.md": "Tools that deploy and update apps/models across many factory or field edge devices.",
    "Docker/Swarm network.md": "Docker Swarm overlay networking so containers on different hosts can reach each other.",
    "Docker/docker container.md": "Running instance of an image — isolated process with its own filesystem and network.",
    "Docker/docker file.md": "Dockerfile — recipe of layers that builds a container image (`FROM`, `RUN`, `CMD`).",
    "Errors/Python.md": "Common Python runtime errors and how to read the traceback to fix them.",
    "ExpressJS/Express-useragent.md": "Express middleware that parses the User-Agent header into browser/OS fields.",
    "ExpressJS/express build.md": "Bundle or compile an Express app for production (for example with esbuild).",
    "ExpressJS/express concepts.md": "Express.js — minimal Node HTTP framework for routes, middleware, and apps.",
    "ExpressJS/express query handler.md": "Validate and parse Express query/body input before your route logic runs.",
    "ExpressJS/pacakges/Express HPP.md": "HPP (HTTP Parameter Pollution) protection — stops duplicate query keys from confusing your app.",
    "ExpressJS/pacakges/Socket IO.md": "Socket.IO — realtime events over WebSocket with HTTP long-poll fallback.",
    "ExpressJS/pacakges/graphql-yoga.md": "GraphQL Yoga — batteries-included GraphQL server that plugs into Node/Express.",
    "ExpressJS/pacakges/uWebSocket.md": "µWebSockets — very fast WebSocket/HTTP server for high-throughput realtime apps.",
    "Feature implementation/Bar code generate feature.md": "Generate barcode images in a Node/Express API (for example with bwip-js).",
    "Feature implementation/Manage cart with session id.md": "Keep a shopping cart keyed by session id across requests without forcing login.",
    "Feature implementation/Push notification integration.md": "Send mobile push via APNs/FCM from your backend with the right certs and tokens.",
    "Firebase/Firebase messaging.md": "Firebase Cloud Messaging — deliver push notifications; batch tokens past the 500 limit.",
    "Firebase/Multicast delivery.md": "FCM multicast — one API call sends the same message to many device tokens.",
    "Firebase/firebase reminders configuration.md": "Wire Firebase Admin + Functions (and mail) to schedule and send reminders.",
    "GIT/git commit template.md": "Point Git at a commit message template so every commit starts with a fixed outline.",
    "GIT/git commit.md": "Create, amend, and inspect commits — the snapshot unit of Git history.",
    "GIT/git diff.md": "Show unstaged, staged, or commit-to-commit file changes.",
    "GIT/git error.md": "Common Git failures (permissions, auth, conflicts) and the usual fixes.",
    "GIT/git guidlines.md": "Commit message and branch conventions (feat/fix style) for readable history.",
    "GIT/git repo config.md": "Repo-level Git settings — user, GPG signing, hooks, and local overrides.",
    "GIT/git ssh config.md": "SSH config for Git remotes — keys, hosts, and required file permissions (600).",
    "GitHub/Github action (2).md": "GitHub Actions — CI/CD workflows that run on push, PR, and schedule events.",
    "GitHub/Github cli (2).md": "`gh` CLI — create PRs, issues, and checks from the terminal.",
    "Kubernates/Kubernetes config.md": "Cluster control-plane config and etcd — the source of truth for cluster state.",
    "Kubernates/Kubernetes services.md": "Stable virtual IP/DNS in front of Pods so clients survive Pod restarts.",
    "LLD/Questions/Connection Pool.md": "LLD exercise: reuse DB connections safely under concurrent load.",
    "LLD/Questions/File based configuration manager.md": "LLD exercise: load and watch system-wide config from files.",
    "LLD/Questions/Logger.md": "LLD exercise: thread-safe logger writing to one shared log file.",
    "Linux.md": "Linux folder hub — kernel, shell, processes, filesystems, and ops commands.",
    "ML/GPT.md": "GPT (GUID Partition Table) — modern disk layout with unique partition IDs; supports huge drives past MBR’s 2 TB limit.",
    "ML/Perceptron.md": "Single-layer neural unit — weighted sum plus threshold; building block of deep nets.",
    "ML/Visualization/data visualization.md": "Charts and plots that make dataset shape, trends, and outliers visible.",
    "ML/claude ai.md": "Claude — Anthropic’s LLM assistant for coding, analysis, and chat.",
    "ML/model tranning.md": "Train a model on labeled data, tune hyperparameters, then evaluate holdout metrics.",
    "ML/prompt enginerring.md": "Craft prompts so an LLM returns reliable, structured answers for your task.",
    "ML/prompt.md": "The input text (and system instructions) you send to a language model.",
    "ML/rank prediction.md": "Predict ordered rankings or scores — recommenders and learning-to-rank tasks.",
    "ML/scikitlearn.md": "scikit-learn — Python library for classic ML: fit, transform, predict pipelines.",
    "Message Broker.md": "Middleware that queues or streams messages between producers and consumers.",
    "Messaging/Kafka/Kafka broker.md": "Kafka broker — server process that stores topic partitions and serves clients.",
    "Messaging/Kafka/Kafka configuration.md": "Kafka broker/client settings that control retention, replication, and throughput.",
    "Messaging/Kafka/Kafka distributed event streaming.md": "Kafka as a distributed log for high-volume event streaming across services.",
    "Messaging/Kafka/Zookeeper.md": "ZooKeeper — older Kafka coordinator for brokers, topics, and controller election.",
    "Messaging/Kafka/kafka producer and consumer.md": "Write events with producers; read topic partitions with consumer groups.",
    "Messaging/Kafka/kafka.md": "Apache Kafka — durable, partitioned log for pub/sub and stream processing.",
    "Messaging/RabbitMQ.md": "RabbitMQ — AMQP message broker with exchanges, queues, and routing keys.",
    "Messaging/SSE (Server-Sent Events).md": "SSE (Server-Sent Events) — server pushes a one-way event stream over HTTP.",
    "Messaging/Web hooks.md": "Webhook — HTTP callback your system POSTs when an event happens.",
    "MongoDB/MongoDB data populate.md": "Fill MongoDB with seed or related documents for apps and tests.",
    "MongoDB/MongoDB query validation.md": "Validate query shape and schema rules before or while writing MongoDB data.",
    "MongoDB/mognodb indexing.md": "MongoDB indexes — speed up filters/sorts; trade write cost and disk for read speed.",
    "MongoDB/mongodb denormalization.md": "Copy related fields into one document to avoid expensive joins/lookups.",
    "MongoDB/mongodb migration.md": "Versioned schema/data changes for MongoDB collections in production.",
    "MongoDB/mongodb schema.md": "Document shape conventions and validation for MongoDB collections.",
    "MongoDB/mongodb shell.md": "Interactive MongoDB shell for ad-hoc queries and admin commands.",
    "MongoDB/mongodb view.md": "Read-only MongoDB view — saved aggregation pipeline exposed like a collection.",
    "MongoDB/mongoose/mongoose custome function.md": "Custom Mongoose instance/static helpers on schemas and models.",
    "MongoDB/mongoose/mongoose methods.md": "Mongoose document and model methods for queries, saves, and hooks.",
    "MongoDB/mongoose/mongoose schema.md": "Mongoose schema — defines fields, types, indexes, and middleware for a model.",
    "MongoDB/mongoose/mongoose.md": "Mongoose — ODM that maps Node objects to MongoDB collections with schemas.",
    "MongoDB/mongosh query.md": "Write and run find/aggregate queries in `mongosh`.",
    "MongoDB/mongosh user management.md": "Create users and roles in MongoDB with `mongosh` admin commands.",
    "MongoDB/mongosh.md": "mongosh — modern MongoDB shell replacing the legacy `mongo` client.",
    "MongoDB/query/mongoDB Group query.md": "`$group` aggregation — bucket documents and compute sums, counts, averages.",
    "MongoDB/query/mongodb lookup query.md": "`$lookup` — join documents from another collection inside an aggregation.",
    "Multicast.md": "One sender to many interested receivers on a multicast group — not the whole LAN.",
    "NextJS/Next JS.md": "Next.js — React framework with routing, SSR/SSG, and API routes.",
    "NextJS/Next js Build.md": "Production `next build` — compiles pages, assets, and the server bundle.",
    "NextJS/NextJS Config.md": "`next.config.js` knobs — rewrites, images, env, and build behavior.",
    "NextJS/NextJS Deployment.md": "Ship a Next.js app to Vercel, Node, or containers with the right build output.",
    "Nginx/Nginx ingress.md": "Kubernetes Ingress controller based on Nginx — HTTP routes into cluster Services.",
    "Nginx/URL Rewriting.md": "Change request URIs with Nginx `rewrite` / `try_files` before proxying or serving.",
    "Nginx/directives.md": "Nginx config directives — context, syntax, and what each common knob does.",
    "Nginx/nginx URL rewrite.md": "Practical Nginx rewrite patterns for pretty URLs and legacy path redirects.",
    "Nginx/nginx core functionality.md": "Nginx core jobs — reverse proxy, static files, TLS termination, and load balancing.",
    "Nginx/nginx fastcgi.md": "Nginx FastCGI pass-through to PHP-FPM or other FastCGI app servers.",
    "Nginx/static file.md": "Serve files directly from disk with Nginx `root`/`alias` and caching headers.",
    "Payments/Payment break down json.md": "JSON shape of a payment breakdown — amounts, fees, tax, and line items.",
    "Payments/Payment integration Strip.md": "Integrate Stripe checkout/charges and webhooks into your backend.",
    "Payments/payment integration razorpay.md": "Integrate Razorpay orders, checkout, and signature verification.",
    "Payments/razorpay integration.md": "Razorpay end-to-end flow — create order, collect pay, confirm on webhook.",
    "Prisma/Prisma.md": "Prisma — typed Node ORM with schema, migrate, and client for SQL databases.",
    "Projects/Project Assignment.md": "Project brief / assignment scope for a build exercise.",
    "Projects/online business PRD.md": "PRD (Product Requirements Doc) for an online business product.",
    "Proxy/Reverse Proxy.md": "Reverse proxy — accepts client traffic and forwards it to backend servers.",
    "Python/ASGI.md": "ASGI (Asynchronous Server Gateway Interface) — async Python web server protocol.",
    "Python/GIL (Global interpreter lock).md": "GIL (Global Interpreter Lock) — only one Python bytecode thread runs at a time in CPython.",
    "Python/Python.md": "Python language hub — runtime, tooling, and debugging entry points.",
    "Python/create python package from source.md": "Turn a folder into an installable Python package other projects can import.",
    "Python/uwsgi.md": "uWSGI — app server that speaks WSGI/HTTP between Nginx/Apache and Python apps.",
    "README.md": "Vault overview — staff-engineer field notes for fast debug and solid configs.",
    "RTQ/RTQ Concepts.md": "Redux Toolkit Query concepts — cached API slices on top of Redux Toolkit.",
    "RTQ/matcher.md": "RTK matchers — react to action types in extraReducers without giant switches.",
    "Rendering performance/composite.md": "Compositing — browser stitches painted layers into the final pixels on screen.",
    "Rendering performance/critical rendering path.md": "Steps from HTML/CSS/JS to first paint — optimize what blocks that path.",
    "TypeScript/Triple-Slash Directives.md": "Triple-slash `///` comments that tell the compiler about refs and deps.",
    "TypeScript/ambient modules.md": "Declare types for a JS library you did not write — no runtime code, just shapes.",
    "TypeScript/class-transformer.md": "Map plain JSON objects to class instances (and back) with decorators.",
    "TypeScript/tsconfig.md": "`tsconfig.json` — compiler options, libs, paths, and project references.",
    "TypeScript/typescript error.md": "Common TypeScript errors and the usual one-line fixes.",
    "TypeScript/typescript extend types.md": "Augment third-party types (for example Express `Request`) via declaration merging.",
    "TypeScript/typescript types.md": "Practical TypeScript types for env, APIs, and everyday app code.",
    "TypeScript/typescript.md": "TypeScript — typed JavaScript with compile-time checks and richer tooling.",
    "Useful prompt for learning with AI chat.md": "Prompt templates that make AI chats better for studying and memorizing topics.",
    "WORKLOG.md": "Session worklog — project status, decisions, and next steps for active demos.",
    "android/adb device.md": "adb (Android Debug Bridge) — talk to a device/emulator for logs, install, shell.",
    "apache/CGI.md": "CGI (Common Gateway Interface) — web server runs an external program per request.",
    "apache/apache command.md": "Apache `a2enmod`/`apachectl` commands to enable modules and manage the service.",
    "apache/apache configurations.md": "Apache httpd/vhost config — reload/restart after changing sites and modules.",
    "apache/fastCGI servers.md": "FastCGI — keep workers warm so dynamic apps avoid CGI’s per-request spawn cost.",
    "compiler/clang.md": "Clang — LLVM front end that compiles C/C++/Objective-C to object code.",
    "compiler/object code.md": "Object code — compiler output (`.o`/`.obj`) before the linker builds a binary.",
    "cookies/cookies configuration.md": "Set-Cookie flags (Expires, Secure, HttpOnly, SameSite) that control browser storage.",
    "cookies/cookies lifecycle.md": "When cookies are created, sent, and deleted across sessions and expirations.",
    "core fundemental.md": "Long-term study map of core CS fundamentals worth mastering over a career.",
    "css/CSS property.md": "How individual CSS properties behave — including display quirks with pseudo-elements.",
    "css/tailwindcss Error.md": "Fix Tailwind “unknown utility” errors — missing `@reference` / content paths.",
    "dart/dart.md": "Dart language notes — constructors, factories, and Flutter’s language base.",
    "flutter/Flutter app icon change.md": "Replace the default Flutter launcher icon with your app’s asset.",
    "flutter/flutter cli.md": "`flutter` CLI — create, run, build, and manage Flutter projects.",
    "flutter/flutter debugging.md": "Debug Flutter apps — DevTools, logs, breakpoints, and widget inspector.",
    "flutter/flutter error.md": "Common Flutter/pub errors and the commands that unblock them.",
    "flutter/flutter widget.md": "Flutter widgets — UI building blocks; prefer builders for lazy screen creation.",
    "golang.md": "Go language folder hub — syntax, concurrency, tooling, and project layout.",
    "golang/Makefile.md": "Makefile patterns for Go builds — `.PHONY` targets and common recipes.",
    "golang/Unbuffered channel.md": "Unbuffered Go channel — send blocks until another goroutine receives.",
    "golang/go callstack.md": "How Go walks the call stack during panics and stack unwinding.",
    "golang/go cli.md": "`go` command — modules, build, test, and run from the terminal.",
    "golang/go data structure.md": "Common Go data structures — maps, slices, trees, and when to use each.",
    "golang/go debugging.md": "Debug Go with Delve — breakpoints, goroutine inspection, and core dumps.",
    "golang/go error.md": "Go error handling — returned `error` values, wrapping, and common panics.",
    "golang/go features.md": "Language features that shape Go style — maps, slices, interfaces, concurrency.",
    "golang/go functions.md": "Go functions — parameters, multiple returns, and method receivers.",
    "golang/go interface.md": "Go interfaces — satisfied implicitly by method sets (structural typing).",
    "golang/go learning.md": "Sequenced prompts and drills for learning Go with an AI tutor.",
    "golang/go package.md": "Go package — a directory of files sharing one `package` name and API.",
    "golang/go project.md": "Starter Go project layout and a small CLI app exercise.",
    "golang/go-routines.md": "Goroutine — lightweight concurrent function scheduled by the Go runtime.",
    "golang/go.md": "Go basics — `package main`, modules, and how a program starts.",
    "helm/cli.md": "`helm` CLI — add repos, install charts, upgrade, and roll back releases.",
    "helm/helm.md": "Helm — package manager for Kubernetes; charts template and version installs.",
    "interview.md": "Interview snippets and quick JS/runtime checks used in screening.",
    "kotlin/kotlin data flow.md": "Kotlin property delegates (`by`) and how data moves through the UI layer.",
    "kotlin/kotlin view.md": "ViewBinding — typed access to layout views without `findViewById`.",
    "npm/moment.md": "moment.js — parse and format dates (legacy; prefer newer date libraries).",
    "npm/mysql2.md": "mysql2 — Node MySQL client; DDL results differ from row result sets.",
    "npm/npm error.md": "Common npm install/runtime errors and the usual cleanup commands.",
    "npm/npm.md": "npm — Node package manager for install, scripts, and global modules.",
    "npm/pnpm cli.md": "pnpm commands — install, approve builds, and workspace workflows.",
    "npm/pnpm logs.md": "Where pnpm stores failure logs and how to read them while debugging installs.",
    "npm/zod.md": "Zod — TypeScript-first schema validation that infers types from parsers.",
    "nvim/commands.md": "Neovim ex-commands and paths (`stdpath`) for config and data dirs.",
    "nvim/nvim setup.md": "Install and bootstrap Neovim with a plugin manager like lazy.nvim.",
    "open standard.md": "Open standard — documented, freely implementable rule set (not a vendor lock-in).",
    "pm2/pm2.md": "PM2 — process manager that keeps Node apps running, clustered, and restarted.",
    "ssh-keygen key validity.md": "An SSH key “works” only if the server trusts the public key — generation alone is not enough.",
    "ssh/SSH authentication.md": "SSH auth — prove you hold the private key (challenge/response or agent).",
    "ssh/ssh agent.md": "ssh-agent — keeps decrypted keys in memory so you type the passphrase once.",
    "ssh/ssh private network.md": "Reach hosts on a private network over SSH — interfaces, routes, and jump hosts.",
    "staff engineer.md": "What staff-plus engineering looks like — scope, influence, and craft over titles.",
    "tmux/tmux.md": "tmux — terminal multiplexer: sessions, windows, and panes that survive disconnects.",
    "vim/ed.md": "ed — line-oriented Unix editor; ancestor of ex/vi command style.",
    "vim/vim commands.md": "Everyday Vim motions, operators, and useful startup flags.",
    "vim/vim config.md": "`.vimrc` settings — indentation, search, and editor behavior.",
    "vim/vim mark.md": "Vim marks — jump back to saved positions in files (`m` / `'`).",
    "vite/vite config.md": "`vite.config` and `import.meta.env` — app config and `VITE_` env exposure.",
    "vite/vite error.md": "Common Vite build/dev failures and how to unblock a broken toolchain.",
    "vite/vite internal.md": "How Vite serves and transforms modules in dev versus production build.",
    "zed/zed debugger.md": "Debug in the Zed editor — console modes and expression evaluation.",
    "zed/zed keybindings.md": "Zed keybindings — resolve LSP popup vs ghost-text conflicts with modifiers.",
}


def main() -> None:
    missing_keys = []
    results = {"added_h1_and_def": 0, "inserted_def": 0, "replaced_def": 0}
    for rel, definition in DEFS.items():
        path = ROOT / rel
        if not path.exists():
            missing_keys.append(rel)
            continue
        action = apply_definition(path, definition)
        results[action] = results.get(action, 0) + 1
    print("applied", sum(results.values()), results)
    if missing_keys:
        print("missing files", len(missing_keys))
        for m in missing_keys:
            print(" ", m)
    # verify coverage vs miss list
    import json, re

    miss = json.loads((ROOT / "tools/miss_defs/all.json").read_text())
    still = []
    for rel in miss:
        p = ROOT / rel
        t = p.read_text(encoding="utf-8", errors="replace")
        h1 = re.search(r"^# .+$", t, re.M)
        if not h1:
            still.append(rel)
            continue
        after = t[h1.end() : h1.end() + 800]
        if not re.search(r"^>\s+(?!\[!)", after, re.M):
            still.append(rel)
    print("still missing after apply:", len(still))
    for s in still[:30]:
        print(" ", s)


if __name__ == "__main__":
    main()
